### ISSUE TITLE
My Mouse automatically teleport to the center of the screen

### ISSUE THREAD

**Issue by T59y9** [NightFyre/DX9-ImGui-Internal-Hook#5]
My Mouse automatically teleport to the center of the screen, so i need to open the game menu to be able to interact with imgui menu, keyboard and mouse blocking works great, but mouse movement isn't blocked, how to fix that?

**Comment by xCENTx** [comment]
You need to block the input being hijacked by the game.

Issues are for issues relating to the Project itself and I will not be making changes to cater to specific games. That is your job as a reverse engineer to figure out on your own.
